### ISSUE TITLE
正会員、賛助会員、協賛会員の意味

### ISSUE THREAD

**Issue by joeartsea** [node-red-jp/rules#1]
正会員、賛助会員、協賛会員それぞれ具体的なイメージは以下でOKですかね？
* 正会員: Node-REDユーザ会参加者（例えばFBグループ、Connpass登録者など）
* 賛助会員: 名前を貸すだけの人？（名誉・著名な人）
* 協賛会員: 会に経済的支援を行う人または組織（スポンサー）
※役員: 正会員から選出（今の運営メンバー、準運営メンバーで構成するつもり）

**Comment by 1ft-seabass** [comment]
はい！私も認識合ってます！
